name: Build_CI

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: git_workflow_images
  IMAGE_TAG: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
          -t $REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

      - name: Scan Docker Image using Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

      - name: Push Docker Image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push \
          $REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Update Kubernetes Manifest
        run: |
          sed -i "s|image:.*|image: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}|g" k8s/deployment.yaml

      - name: Commit Updated Manifest
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add k8s/deployment.yaml
          git commit -m "Update image to ${{ env.IMAGE_TAG }}" || echo "No changes"
          git 
