name: Build_CI

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: public.ecr.aws/c8e3l5e6/git_workflow_images  # Replace with your registry alias
  ECR_REPOSITORY: git_workflow_images
  IMAGE_TAG: ${{ github.sha }}

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        run: |
          aws ecr-public get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker Image
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

      - name: Scan Docker Image using Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          exit-code: '0'
          severity: 'HIGH,CRITICAL'

      - name: Push Docker Image
        run: |
          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Kubernetes Manifest
        run: |
          sed -i "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" k8s/deployment.yaml

      - name: Commit Updated Manifest
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git add k8s/deployment.yaml
          git commit -m "Update image to $IMAGE_TAG" || echo "No changes"
          git push